// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Aw4_j-wqw9cimD85xBNa3B-4xHhNrA8',
    appId: '1:964639207525:web:d9501bd72e98697364568c',
    messagingSenderId: '964639207525',
    projectId: 'thevolunteeringapp',
    authDomain: 'thevolunteeringapp.firebaseapp.com',
    storageBucket: 'thevolunteeringapp.appspot.com',
    measurementId: 'G-KT7MVKF30B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrVx9Oou4H67nbwkBNSQj1UGx5RrCAf0',
    appId: '1:964639207525:android:ab56295b16f53bbe64568c',
    messagingSenderId: '964639207525',
    projectId: 'thevolunteeringapp',
    storageBucket: 'thevolunteeringapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXSL0LGhuHn5eMWsGlcrmSaMpFN08p2Q',
    appId: '1:964639207525:ios:923d8d119cf669f164568c',
    messagingSenderId: '964639207525',
    projectId: 'thevolunteeringapp',
    storageBucket: 'thevolunteeringapp.appspot.com',
    iosBundleId: 'com.example.voluntariadoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYXSL0LGhuHn5eMWsGlcrmSaMpFN08p2Q',
    appId: '1:964639207525:ios:b76b6fe40be6488764568c',
    messagingSenderId: '964639207525',
    projectId: 'thevolunteeringapp',
    storageBucket: 'thevolunteeringapp.appspot.com',
    iosBundleId: 'com.example.voluntariadoApp.RunnerTests',
  );
}
